import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'
import './globals.css'
import { PROJECTNAME } from '@/common/copy'
import RainbowKitGlobalProvider from '@/wallet/rainbowkit-provider'

const manrope = Manrope({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: PROJECTNAME,
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <RainbowKitGlobalProvider>
          {children}
        </RainbowKitGlobalProvider>
      </body>
    </html>
  )
}
